---
# Default values for kore.
nameOverride: ""
ca:
  generate: true
  secretName: kore-ca
redis:
  version: 5.0
mysql:
  image: mariadb
  version: bionic
  pvc:
    create: true
    storageClass: ""
    size: 10Gi
idp:
  client_id: ""
  client_secret: ""
  server_url: ""
  user_claims:
    - preferred_username
    - email
    - name
    - username
  client_scopes:
    - email
    - profile
    - offline_access
api:
  feature_gates: []
  verbose: false
  endpoint:
    url: http://localhost:10080
    detect: false
  images: {}
  ingress:
    enabled: false
    hostname: localhost:10080
    tls_secret: ""
    annotations: {}
  port: 10080
  hostPort: ""
  serviceType: ClusterIP
  image: quay.io/appvia/kore-apiserver
  version: v0.0.22
  auth_plugins:
    - basicauth
    - admintoken
    - openid
  replicas: 2
ui:
  feature_gates: []
  endpoint:
    url: http://localhost:3000
    detect: false
  ingress:
    enabled: false
    hostname: localhost:3000
    tls_secret: ""
    annotations: {}
  port: 3000
  hostPort: ""
  serviceType: ClusterIP
  image: quay.io/appvia/kore-ui
  version: v0.0.22
  replicas: 2
  show_prototypes: false
kubectl:
  version: 1.16
