
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: plans.config.kore.appvia.io
spec:
  group: config.kore.appvia.io
  names:
    kind: Plan
    listKind: PlanList
    plural: plans
    singular: plan
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Plan is the Schema for the plans API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PlanSpec defines the desired state of Plan
          properties:
            description:
              description: Description provides a summary of the configuration provided
                by this plan
              minLength: 1
              type: string
            kind:
              description: Resource refers to the resource type this is a plan for
              minLength: 1
              type: string
            labels:
              additionalProperties:
                type: string
              description: Labels is a collection of labels for this plan
              type: object
            summary:
              description: Summary provides a short title summary for the plan
              minLength: 1
              type: string
            values:
              description: Values are the key values to the plan
              type: object
              x-kubernetes-preserve-unknown-fields: true
          required:
          - description
          - kind
          - summary
          - values
          type: object
        status:
          description: PlanStatus defines the observed state of Plan
          properties:
            conditions:
              description: Conditions is a set of condition which has caused an error
              items:
                description: Condition is a reason why something failed
                properties:
                  detail:
                    description: Detail is a actual error which might contain technical
                      reference
                    type: string
                  message:
                    description: Message is a human readable message
                    type: string
                required:
                - detail
                - message
                type: object
              type: array
            status:
              description: Status is overall status of the workspace
              type: string
          required:
          - status
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
