
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: idp.core.kore.appvia.io
spec:
  group: core.kore.appvia.io
  names:
    kind: IDP
    listKind: IDPList
    plural: idp
    singular: idp
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: IDP is the Schema for the class API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: IDPSpec defines the spec for a configured instance of an IDP
          properties:
            config:
              description: IDPConfig
              properties:
                github:
                  description: Google represents a Google IDP config
                  properties:
                    clientID:
                      description: ClientID is the field name in a Github OAuth app
                      type: string
                    clientSecret:
                      description: ClientSecret is the field name in a Github OAuth
                        app
                      type: string
                    orgs:
                      description: ClientSecret is the list of possible Organisations
                        in Github the user must be part of
                      items:
                        type: string
                      type: array
                  required:
                  - clientID
                  - clientSecret
                  - orgs
                  type: object
                google:
                  description: GoogleIDP provides config for a Google Identity provider
                  properties:
                    clientID:
                      description: ClientID is the field name in a Google OAuth app
                      type: string
                    clientSecret:
                      description: ClientSecret is the field name in a Google OAuth
                        app
                      type: string
                    domains:
                      description: Domains are the google accounts whitelisted for
                        authentication
                      items:
                        type: string
                      type: array
                  required:
                  - clientID
                  - clientSecret
                  - domains
                  type: object
                oidc:
                  description: OIDCIDP config for a generoc Open ID Connect provider
                  properties:
                    clientID:
                      description: ClientID provides the OIDC client ID string
                      type: string
                    clientSecret:
                      description: ClientSecret provides the OIDC client secret string
                      type: string
                    issuer:
                      description: Issuer provides the IDP URL
                      type: string
                  required:
                  - clientID
                  - clientSecret
                  - issuer
                  type: object
                saml:
                  description: SAMLIDP provides configuration for a generic SAML Identity
                    provider
                  properties:
                    allowedGroups:
                      description: AllowedGroups provides a list of allowed groups
                      items:
                        type: string
                      type: array
                    caData:
                      description: CAData is byte array representing the PEM data
                        for the IDP signing CA
                      format: byte
                      type: string
                    emailAttr:
                      description: EmailAttr attribute in the returned assertion to
                        map to ID token claims
                      type: string
                    groupsAttr:
                      description: GroupsAttr attribute in the returned assertion
                        to map to ID token claims
                      type: string
                    groupsDelim:
                      description: GroupsDelim characters used to split the single
                        groups field to obtain the user group membership
                      type: string
                    ssoURL:
                      description: SSOURL provides the SSO URL used for POST value
                        to IDP
                      type: string
                    usernameAttr:
                      description: UsernameAttr attribute in the returned assertion
                        to map to ID token claims
                      type: string
                  required:
                  - caData
                  - emailAttr
                  - ssoURL
                  - usernameAttr
                  type: object
              type: object
            displayName:
              description: DisplayName
              type: string
          required:
          - config
          - displayName
          type: object
        status:
          description: IDPStatus defines the observed state of an IDP (ID Providers)
          properties:
            conditions:
              description: Conditions is a set of condition which has caused an error
              items:
                description: Condition is a reason why something failed
                properties:
                  detail:
                    description: Detail is a actual error which might contain technical
                      reference
                    type: string
                  message:
                    description: Message is a human readable message
                    type: string
                required:
                - detail
                - message
                type: object
              type: array
            status:
              description: Status is overall status of the IDP configuration
              type: string
          required:
          - status
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
