
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
  creationTimestamp: null
  name: users.org.kore.appvia.io
spec:
  group: org.kore.appvia.io
  names:
    kind: AuditEvent
    listKind: AuditEventList
    plural: users
    singular: auditevent
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: AuditEvent is the Schema for the users API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AuditEventSpec defines the desired state of User
          properties:
            createdAt:
              description: CreatedAt is the timestamp of record creation
              format: date-time
              type: string
            message:
              description: Message is event message itself
              type: string
            resource:
              description: Resource is the name of the resource in question namespace/name
              type: string
            resourceUID:
              description: ResourceUID is a unique id for the resource
              type: string
            team:
              description: Team is the team whom event may be associated to
              type: string
            type:
              description: Type is the type of event
              type: string
            user:
              description: User is the user which the event is related
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
